/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BetCreateNestedManyWithoutAppUsersInput } from "./BetCreateNestedManyWithoutAppUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { NotificationCreateNestedManyWithoutAppUsersInput } from "./NotificationCreateNestedManyWithoutAppUsersInput";
import { UserAchievementCreateNestedManyWithoutAppUsersInput } from "./UserAchievementCreateNestedManyWithoutAppUsersInput";

@InputType()
class AppUserCreateInput {
  @ApiProperty({
    required: false,
    type: () => BetCreateNestedManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => BetCreateNestedManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => BetCreateNestedManyWithoutAppUsersInput, {
    nullable: true,
  })
  bets?: BetCreateNestedManyWithoutAppUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutAppUsersInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutAppUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserAchievementCreateNestedManyWithoutAppUsersInput,
  })
  @ValidateNested()
  @Type(() => UserAchievementCreateNestedManyWithoutAppUsersInput)
  @IsOptional()
  @Field(() => UserAchievementCreateNestedManyWithoutAppUsersInput, {
    nullable: true,
  })
  userAchievements?: UserAchievementCreateNestedManyWithoutAppUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { AppUserCreateInput as AppUserCreateInput };
