/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { GameRoom } from "./GameRoom";
import { GameRoomCountArgs } from "./GameRoomCountArgs";
import { GameRoomFindManyArgs } from "./GameRoomFindManyArgs";
import { GameRoomFindUniqueArgs } from "./GameRoomFindUniqueArgs";
import { CreateGameRoomArgs } from "./CreateGameRoomArgs";
import { UpdateGameRoomArgs } from "./UpdateGameRoomArgs";
import { DeleteGameRoomArgs } from "./DeleteGameRoomArgs";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { GameRoomService } from "../gameRoom.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GameRoom)
export class GameRoomResolverBase {
  constructor(
    protected readonly service: GameRoomService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GameRoom",
    action: "read",
    possession: "any",
  })
  async _gameRoomsMeta(
    @graphql.Args() args: GameRoomCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GameRoom])
  @nestAccessControl.UseRoles({
    resource: "GameRoom",
    action: "read",
    possession: "any",
  })
  async gameRooms(
    @graphql.Args() args: GameRoomFindManyArgs
  ): Promise<GameRoom[]> {
    return this.service.gameRooms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GameRoom, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GameRoom",
    action: "read",
    possession: "own",
  })
  async gameRoom(
    @graphql.Args() args: GameRoomFindUniqueArgs
  ): Promise<GameRoom | null> {
    const result = await this.service.gameRoom(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GameRoom)
  @nestAccessControl.UseRoles({
    resource: "GameRoom",
    action: "create",
    possession: "any",
  })
  async createGameRoom(
    @graphql.Args() args: CreateGameRoomArgs
  ): Promise<GameRoom> {
    return await this.service.createGameRoom({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GameRoom)
  @nestAccessControl.UseRoles({
    resource: "GameRoom",
    action: "update",
    possession: "any",
  })
  async updateGameRoom(
    @graphql.Args() args: UpdateGameRoomArgs
  ): Promise<GameRoom | null> {
    try {
      return await this.service.updateGameRoom({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GameRoom)
  @nestAccessControl.UseRoles({
    resource: "GameRoom",
    action: "delete",
    possession: "any",
  })
  async deleteGameRoom(
    @graphql.Args() args: DeleteGameRoomArgs
  ): Promise<GameRoom | null> {
    try {
      return await this.service.deleteGameRoom(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Message], { name: "messages" })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  async findMessages(
    @graphql.Parent() parent: GameRoom,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
