/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Tournament } from "./Tournament";
import { TournamentCountArgs } from "./TournamentCountArgs";
import { TournamentFindManyArgs } from "./TournamentFindManyArgs";
import { TournamentFindUniqueArgs } from "./TournamentFindUniqueArgs";
import { CreateTournamentArgs } from "./CreateTournamentArgs";
import { UpdateTournamentArgs } from "./UpdateTournamentArgs";
import { DeleteTournamentArgs } from "./DeleteTournamentArgs";
import { TournamentService } from "../tournament.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Tournament)
export class TournamentResolverBase {
  constructor(
    protected readonly service: TournamentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Tournament",
    action: "read",
    possession: "any",
  })
  async _tournamentsMeta(
    @graphql.Args() args: TournamentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Tournament])
  @nestAccessControl.UseRoles({
    resource: "Tournament",
    action: "read",
    possession: "any",
  })
  async tournaments(
    @graphql.Args() args: TournamentFindManyArgs
  ): Promise<Tournament[]> {
    return this.service.tournaments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Tournament, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Tournament",
    action: "read",
    possession: "own",
  })
  async tournament(
    @graphql.Args() args: TournamentFindUniqueArgs
  ): Promise<Tournament | null> {
    const result = await this.service.tournament(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tournament)
  @nestAccessControl.UseRoles({
    resource: "Tournament",
    action: "create",
    possession: "any",
  })
  async createTournament(
    @graphql.Args() args: CreateTournamentArgs
  ): Promise<Tournament> {
    return await this.service.createTournament({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Tournament)
  @nestAccessControl.UseRoles({
    resource: "Tournament",
    action: "update",
    possession: "any",
  })
  async updateTournament(
    @graphql.Args() args: UpdateTournamentArgs
  ): Promise<Tournament | null> {
    try {
      return await this.service.updateTournament({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Tournament)
  @nestAccessControl.UseRoles({
    resource: "Tournament",
    action: "delete",
    possession: "any",
  })
  async deleteTournament(
    @graphql.Args() args: DeleteTournamentArgs
  ): Promise<Tournament | null> {
    try {
      return await this.service.deleteTournament(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
